function genQuote() {
  var randNum = Math.floor(Math.random() * 16) + 1;
  document.getElementById('quote').innerHTML = quotes[randNum];
  document.getElementById('quote2').innerHTML = quotes[randNum];
}

//quote array
var quotes = ["Blank", "\"Either I will find a way, or I will make one.\"<br><br> - Philip Sidney", "\"Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.\"<br><br>- Thomas A. Edison", "\"You are never too old to set another goal or to dream a new dream.\"<br><br>- C.S Lewis", "\"If you can dream it, you can do it.\"<br><br>- Walt Disney", "\"Never give up, for that is just the place and time that the tide will turn.\"<br><br>- Harriet Beecher Stowe", "\"I know where I'm going and I know the truth, and I don't have to be what you want me to be. I'm free to be what I want.\"<br><br>- Muhammad Ali", "\"If you always put limit on everything you do, physical or anything else. It will spread into your work and into your life. There are no limits. There are only plateaus, and you must not stay there, you must go beyond them.\"<br><br>- Bruce Lee", "\"Design is a funny word. Some people think design is how it looks. But of course, if you dig deeper, it's really how it works.\"<br><br> - Steve Jobs", "\"Whatever we plant in our subconscious mind and nourish with repetition and emotion will one day become reality\"<br><br>- Earl Nightingale", "\"Showing off is the fool’s idea of glory\"<br><br>- Bruce", "\"The master has failed more times than the beginner has ever tried\"<br><br>- Stephen McCranie", "\"Opportunities to find our deeper powers come when life seems most challenging\"<br><br>- Joseph Campbell", "\"You can’t get much done in life if you only work on the days when you feel good.\"<br><br>- Jerry West", "\"Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.\"<br><br>- Earl Nightingale", "\"If people arent laughing at your dreams, your dreams arent big enough.\"<br><br>- Grayson Marshall",
];
